### ISSUE TITLE
Not able to access whatsapp setting page 

### ISSUE THREAD

**Issue by maxfu9** [shridarpatil/frappe_whatsapp#30]
for reference see the screenshot 
<img width="1605" alt="Screenshot 2023-05-28 at 8 49 45 AM" src="https://github.com/shridarpatil/frappe_whatsapp/assets/29174889/df462a77-a7c7-4afc-887e-eb9a0fb35d06">

>

**Comment by maxfu9** [comment]
@shridarpatil Yes it is installed and all other docs are accessible

**Comment by maxfu9** [comment]
@ I noticed that doctype exists but no setting page 
<img width="1677" alt="Screenshot 2023-06-01 at 12 19 50 AM" src="https://github.com/shridarpatil/frappe_whatsapp/assets/29174889/1832dd7e-be26-42c6-a8d3-2c951489b97c">

**Comment by maxfu9** [comment]
@shridarpatil any solution?

**Comment by shridarpatil** [comment]
can you try reinstalling the app?

**Comment by maxfu9** [comment]
**I tried to uninstall to reinstall and faced the following error** 
`Deleting Module 'Frappe Whatsapp'
* removing DocType 'WhatsApp Settings'...
* removing DocType 'WhatsApp Message'...
* removing DocType 'WhatsApp Notification'...
* removing DocType 'WhatsApp Templates'...
* removing DocType 'WhatsApp Message Fields'...
* removing DocType 'WhatsApp Notification Log'...
* removing Module Def 'Frappe Whatsapp'...
* dropping Table for 'WhatsApp Message Fields'...
* dropping Table for 'WhatsApp Notification'...
* dropping Table for 'WhatsApp Notification Log'...
* dropping Table for 'WhatsApp Templates'...
* dropping Table for 'WhatsApp Message'...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/site.py", line 803, in uninstall
    remove_app(app_name=app, dry_run=dry_run, yes=yes, no_backup=no_backup, force=force)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/installer.py", line 380, in remove_app
    frappe.get_single("Installed Applications").update_versions()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/core/doctype/installed_applications/installed_applications.py", line 27, in update_versions
    self.save()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_before_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1039, in run_before_save_methods
    self.run_method("before_validate")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe_whatsapp/frappe_whatsapp/utils/__init__.py", line 17, in run_server_script_for_doc_event
    notification = get_notifications_map().get(
  File "/home/ubuntu/frappe-bench/apps/frappe_whatsapp/frappe_whatsapp/utils/__init__.py", line 36, in get_notifications_map
    enabled_whatsapp_notifications = frappe.get_all(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1925, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 1897, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/db_query.py", line 190, in execute
    self.columns = self.get_table_columns()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/db_query.py", line 533, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/meta.py", line 75, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/database/database.py", line 1175, in get_table_columns
    raise self.TableMissingError("DocType", doctype)
pymysql.err.ProgrammingError: ('DocType', 'WhatsApp Notification')`

**Comment by maxfu9** [comment]
@shridarpatil Have you find any solution?
