### ISSUE TITLE
send notification with variables on after submit fails

### ISSUE THREAD

**Issue by lansgt** [shridarpatil/frappe_whatsapp#75]
Hi,

- Send notification without variables on doctype event After Save, works
- Send notification without variables on doctype event After Submit, works
- Send notification with variables on doctype event After Save, works
- Send notification with variables on doctype event After Submit, fails

Please help

### App Versions
```
{
	"custom_doctypes": "0.0.1",
	"erpnext": "15.23.3",
	"exchangedata": "0.0.1",
	"frappe": "15.27.0",
	"frappe_whatsapp": "v1.0.7",
	"healthcare": "14.0.3",
	"hrms": "15.21.0",
	"leave_app": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Leave Application/LIC-10937
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe_whatsapp/frappe_whatsapp/frappe_whatsapp/doctype/whatsapp_notification/whatsapp_notification.py", line 186, in notify
    headers=headers, data=json.dumps(data)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe_whatsapp/frappe_whatsapp/frappe_whatsapp/doctype/whatsapp_notification/whatsapp_notification.py", line 205, in notify
    response = frappe.flags.integration_request.json()['error']
AttributeError: 'NoneType' object has no attribute 'json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/frappe_whatsapp/frappe_whatsapp/utils/__init__.py", line 27, in run_server_script_for_doc_event
    ).send_template_message(doc)
  File "apps/frappe_whatsapp/frappe_whatsapp/frappe_whatsapp/doctype/whatsapp_notification/whatsapp_notification.py", line 170, in send_template_message
    self.notify(data)
  File "apps/frappe_whatsapp/frappe_whatsapp/frappe_whatsapp/doctype/whatsapp_notification/whatsapp_notification.py", line 216, in notify
    "meta_data": frappe.flags.integration_request.json()
AttributeError: 'NoneType' object has no attribute 'json'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"LIC-10937\",\"owner\":\"samp@samp.com\",\"creation\":\"2024-06-12 11:02:36.511016\",\"modified\":\"2024-06-12 13:50:48.001979\",\"modified_by\":\"samp@samp.com\",\"docstatus\":0,\"idx\":0,\"naming_series\":\"LIC-.\",\"employee\":\"CUE-10379\",\"employee_name\":\"Name Name\",\"custom_col_dpi\":\"246630101\",\"fecha_crea\":\"2024-06-12\",\"tipo_lic\":\"\",\"leave_type\":\"Vacaciones\",\"custom_empjoining\":\"2023-05-19\",\"custom_emp_branch\":\"Planta\",\"company\":\"SAMP\",\"department\":\"Pintura Máquina - L\",\"custom_col_phone\":\"47573540\",\"from_date\":\"2024-06-13\",\"to_date\":\"2024-06-27\",\"half_day\":0,\"custom_hours\":0,\"total_leave_days\":13,\"fecha_alta_vac\":\"2023-05-19\",\"inic_per_vac\":\"2023-05-19\",\"fin_per_vac\":\"2024-05-18\",\"fecha_reg_lab\":\"2024-06-28\",\"hora_inic_sol\":\"0:00:00\",\"hora_fin_sol\":\"0:00:00\",\"hora_inic\":\"0:00:00\",\"hora_fin\":\"0:00:00\",\"hora_cita\":\"0:00:00\",\"description\":\"Vacaciones programadas por aniversario laboral\",\"doc_sol\":\"No Aplica\",\"const\":\"No Aplica\",\"leave_balance\":15,\"leave_approver\":\"samp@samp.com\",\"leave_approver_name\":\"samp@samp.com\",\"follow_via_email\":1,\"posting_date\":\"2024-06-12\",\"status\":\"Approved\",\"proc_conta\":0,\"letter_head\":\"Membrete LANS\",\"doctype\":\"Leave Application\",\"half_day_date\":\"\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery3700086204198274978161": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 4620,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'json'",
	"exc_type": "AttributeError",
	"_exc_source": "frappe_whatsapp (app)"
}
```

**Comment by shridarpatil** [comment]
Added a fix for this.
